import { normalize } from './text.js'

// Principales villes françaises et leur département : sert à reconnaître "Villeurbanne (69)"
// quand on cherche "Lyon", et à repérer la ville dans l'en-tête d'un CV.
const CITIES: [string, string][] = [
  ['Paris', '75'],
  ['Marseille', '13'],
  ['Lyon', '69'],
  ['Toulouse', '31'],
  ['Nice', '06'],
  ['Nantes', '44'],
  ['Montpellier', '34'],
  ['Strasbourg', '67'],
  ['Bordeaux', '33'],
  ['Lille', '59'],
  ['Rennes', '35'],
  ['Reims', '51'],
  ['Toulon', '83'],
  ['Saint-Étienne', '42'],
  ['Le Havre', '76'],
  ['Grenoble', '38'],
  ['Dijon', '21'],
  ['Angers', '49'],
  ['Nîmes', '30'],
  ['Villeurbanne', '69'],
  ['Clermont-Ferrand', '63'],
  ['Le Mans', '72'],
  ['Aix-en-Provence', '13'],
  ['Brest', '29'],
  ['Tours', '37'],
  ['Amiens', '80'],
  ['Limoges', '87'],
  ['Annecy', '74'],
  ['Perpignan', '66'],
  ['Boulogne-Billancourt', '92'],
  ['Metz', '57'],
  ['Besançon', '25'],
  ['Orléans', '45'],
  ['Rouen', '76'],
  ['Mulhouse', '68'],
  ['Caen', '14'],
  ['Nancy', '54'],
  ['Saint-Denis', '93'],
  ['Argenteuil', '95'],
  ['Montreuil', '93'],
  ['Roubaix', '59'],
  ['Tourcoing', '59'],
  ['Avignon', '84'],
  ['Nanterre', '92'],
  ['Poitiers', '86'],
  ['Versailles', '78'],
  ['Courbevoie', '92'],
  ['Pau', '64'],
  ['La Rochelle', '17'],
  ['Calais', '62'],
  ['Cannes', '06'],
  ['Saint-Nazaire', '44'],
  ['Colmar', '68'],
  ['Bourges', '18'],
  ['Vannes', '56'],
  ['Lorient', '56'],
  ['Quimper', '29'],
  ['Valence', '26'],
  ['Chambéry', '73'],
  ['Troyes', '10'],
  ['Niort', '79'],
  ['La Défense', '92'],
  ['Puteaux', '92'],
  ['Issy-les-Moulineaux', '92'],
  ['Massy', '91'],
  ['Évry', '91'],
  ['Cergy', '95'],
  ['Créteil', '94'],
  ['Bayonne', '64'],
  ['Sophia Antipolis', '06'],
  ['Béziers', '34'],
  ['Ajaccio', '2A'],
  ['Bastia', '2B'],
  ['Angoulême', '16'],
  ['Laval', '53'],
  ['Chartres', '28'],
]

export const CITY_DEPARTMENTS: ReadonlyMap<string, string> = new Map(
  CITIES.map(([name, dep]) => [normalize(name), dep]),
)
export const CITY_NAMES: ReadonlyMap<string, string> = new Map(CITIES.map(([name]) => [normalize(name), name]))
